title = "Boiding"
authors = ["Jan-Erik Rediger", "Daan van Berkel"]
description = "A workbook for the boiding workshop"

source = "src"

[output.html]
destination = "docs"
mathjax-support = true
additional-js = ["src/js/widgets.js"]