[book]
title = "Boiding"
authors = ["Jan-Erik Rediger", "Daan van Berkel"]
description = "A workbook for the boiding workshop"
src = "src"
lang = "en"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
additional-js = ["src/js/widgets.js"]